### ISSUE TITLE
KeyError: u'ap-east-1'

### ISSUE THREAD

**Issue by jgardiner68** [erans/ec2instancespricing#59]
Hello

I am getting an error:

KeyError: u'ap-east-1'

when trying to run the CLI

Traceback (most recent call last):
  File "Library/Python/2.7/bin/ec2instancespricing.py", line 4, in <module>
    __import__('pkg_resources').run_script('ec2instancespricing==0.1', 'ec2instancespricing.py')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1674, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/jamesgardiner/Library/Python/2.7/lib/python/site-packages/ec2instancespricing-0.1-py2.7.egg/EGG-INFO/scripts/ec2instancespricing.py", line 852, in <module>

  File "/Users/jamesgardiner/Library/Python/2.7/lib/python/site-packages/ec2instancespricing-0.1-py2.7.egg/EGG-INFO/scripts/ec2instancespricing.py", line 799, in _get_data

  File "/Users/jamesgardiner/Library/Python/2.7/lib/python/site-packages/ec2instancespricing-0.1-py2.7.egg/EGG-INFO/scripts/ec2instancespricing.py", line 737, in get_ec2_spot_instances_prices

  File "/Users/jamesgardiner/Library/Python/2.7/lib/python/site-packages/ec2instancespricing-0.1-py2.7.egg/EGG-INFO/scripts/ec2instancespricing.py", line 542, in get_ec2_instances_prices

**Comment by erans** [comment]
Just pushed a fix with the new zone.
